---
# tasks file for common

- name: Install dependencies on Debian-based systems (Ubuntu or similar)
  package:
    name:
      - python3
      - git
    state: present
  when: ansible_facts['os_family'] == 'Debian'

