---
- name: Install Kubernetes packages on master
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Initialize Kubernetes master node
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init
  when: kubeadm_init is not defined

- name: Set up kubeconfig for master node
  copy:
    dest: "{{ ansible_env.HOME }}/.kube/config"
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
    mode: 0600

- name: Apply Flannel CNI for networking
  command: kubectl apply -f /tmp/kube-flannel.yml
