# tasks file for master

- name: Install dependencies on Debian-based systems (for Kubernetes repository)
  package:
    name:
      - apt-transport-https
      - gnupg
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Ensure apt sources directory exists (for Debian-based systems)
  file:
    path: /etc/apt/sources.list.d/
    state: directory
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Kubernetes apt repository (for Debian-based systems)
  shell: |
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/k8s-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/k8s-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-{{ ansible_facts['distribution'] | lower }} main" > /etc/apt/sources.list.d/kubernetes.list
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Update package index
  apt:
    update_cache: yes
  become: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Verify if Kubernetes packages are available
  shell: apt-cache policy kubelet | grep Candidate
  register: kubelet_check
  ignore_errors: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Kubernetes packages on master
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  become: yes

- name: Initialize Kubernetes master node
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_init
  become: yes
  when: kubeadm_init is not defined

- name: Set up kubeconfig for master node
  copy:
    dest: "{{ ansible_env.HOME }}/.kube/config"
    content: "{{ lookup('file', '/etc/kubernetes/admin.conf') }}"
    mode: 0600
  become: yes

- name: Install flannel network plugin
  kubernetes.core.k8s:
    kubeconfig: "/etc/kubernetes/admin.conf"
    state: present
    definition: "{{ lookup('file', 'flannel.yaml') }}"
  become: yes

- name: Remove taint from master node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  become: yes
