---
- name: Provision Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Master Node
  hosts: master
  become: yes
  roles:
    - master

- name: Setup Worker Nodes
  hosts: worker
  become: yes
  roles:
    - worker
