---
- name: Wait for master API to be reachable
  wait_for:
    host: "{{ hostvars['k8s-master-1']['ansible_default_ipv4']['address'] }}"
    port: 6443
    timeout: 30

- name: Join the cluster
  shell: "{{ hostvars['k8s-master-1'].join_command }} >> /home/ubuntu/node_joined.log"
  args:
    creates: /home/ubuntu/node_joined.log
