---
- name: Install Kubernetes packages on worker
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Join worker node to master
  command: kubeadm join {{ hostvars['master']['kubeadm_init'].stdout_lines | last }} --token {{ master_token }} --discovery-token-ca-cert-hash sha256:{{ discovery_token_hash }}
  when: ansible_facts['os_family'] == 'Debian' and ansible_hostname != 'master'
